# Site settings
title: Dong Liang's CV 
description: ddbullfrog's CV
favicon: /resumecard/assets/img/avatar.JPG
baseurl: https://ddbullfrog.github.io/resumecard
url: https://ddbullfrog.github.io/resumecard
rss_url: /resumecard/pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Dong Liang
  title: Java Developer
  address: Auckland, New Zealand
  email: dongg.liang@gmail.com
  link: http://ddbullfrog.com
  weibo:
  github: ddbullfrog
  linkedin: ddbullfrog
  twitter: ddbullfrog
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Key lab of Quantum Infomation, CAS
      location: Hefei, China
      title: Research Assistant
      started: 2015
      duration: (2015 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Collaborative Innovation Center for Advanced Fusion Energy & Plasma Science
      location: Hefei, China
      title: Research Assistant
      started: 2014
      duration: (2014 - 2015)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: University of Science and Technology of China
      location: Hefei, China
      degree: Bachelor
      major: Physics & Computer Science
      started: 2013
      duration: (2013 - 2017)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Franch
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: C/C++
      percentage: 80%
    - skill2:
      name: Julia
      percentage: 80%
    - skill3:
      name: Python
      percentage: 80%
    - skill4:
      name: Mathematica
      percentage: 50%
    - skill5:
      name: HTML
      percentage: 90%
    - skill6:
      name: Javascript
      percentage: 40%